### ISSUE TITLE
Closed case

### ISSUE THREAD

**Issue by jaumard** [matrix-io/MATRIX-Creator-Case#2]
Hello,

This case look nice but for me it's not finished... Would be nice to have a transparent layer above the leds and plain color on top of the board to close completely the case. Is it something doable ? I never use/done 3D printing...
If it's possible what about the sensors ? Like IR will still work if we cover the board ? 

Thanks

**Comment by al13nus** [comment]
I don't understand, why they show a really nice case in videos but don't provide the print files to the buyers...

**Comment by AlieGG** [comment]
Hello @mxiMy. To clarify, the nice case you have seen in videos is an injection molded case for another product of ours and not the MATRIX Creator. We do not provide the print files for that case because it would be impossible to 3D print.

The reason why the 3D printable case for the MATRIX Creator does not have a lid is because it would be very difficult for a 3D printer to print a lid that would have holes and/or different materials for the 8 microphones, 35 LED's, temperature sensor, humidity sensor, IR TX/RX, etc. Taking into account the limitations of an affordable 3D printer, not having a lid is the best way to not interfere with the functions of the MATRIX Creator.

**Comment by al13nus** [comment]
Hello @Alfred-AdMobilize,

big thanks for this feedback. I bought the MATRIX Voice and what I'm trying to have is this nice "computer vision device, that recognizes when you get home" like in the video where the women cames home. So if I understood you right, its not possible to print this case at 3D Hubs if you would provide the files?

Best, 
mxiMy

**Comment by AlieGG** [comment]
Hello @mxiMy,

The video you are referencing is for our MATRIX Kickstarter project and is not at all about the MATRIX Voice. In fact that video was released over a year before we announced the MATRIX Voice.

Correct, even if we posted the files for that case it would be impossible to 3D print it as it is made for injection molding and not 3D printing. Additionally, the MATRIX Voice has a smaller form factor than the boards intended for that case so none of the holes or mounting points would match.

Regards,
